export const caseDataSet = {
  'CN-001': {
    caseNumber: 'CN-001',
    caseStatus: 'Resolved',
    agentPerformance: 'Below Expectations',
    agentPerformanceScore: '2.6/5',
    agentQaRating: 'Needs Improvement',
    agentQaScore: '33/50 (66%)',
    agentAction:
      "The agent's performance needs significant improvement, particularly in proactive communication, taking ownership, and managing the case resolution effectively. The lack of follow-up and timely updates impacted customer satisfaction.",
    caseType: 'Support',
    severity: 'High',
    summary:
      'The customer reported a vehicle breakdown due to high temperature, followed by coordination for assistance and a final inquiry about the repair status. The customer expressed dissatisfaction and confusion during the calls, but the issue was ultimately resolved.',
    issueBucket: 'Vehicle Breakdown',
    issueCause: 'Due to high temperature',
    brandPerception: 'Negative',
    brandLoyalty: 'Immediate negative impact due to poor service experience.',
    brandTrust:
      '1- Diminished trust in the brand.\n2- Decreased future purchases or service requests.',
    brandMentionsCustomer: 'No',
    brandMentionsAgent:
      '1- Can the vehicle go to a Tata Motors workshop?\n2- Is it a Tata vehicle\n3- Is the vehicle able to go to a Tata Motors workshop?',
    competitorMentions: 'No',
    anticipatedSentiment:
      '1- Frustration leading to negative word-of-mouth.\n2- Reduced brand loyalty.',
    issuesAffectingSentiment:
      '1- Recurring overheating issue, unresolved after previous repairs.\n2- Replaced parts did not resolve the problem, indicating poor diagnostic or repair quality.\n3- Perceived lack of actionable support or knowledgeable assistance from staff.\n4- Repeatedly asking for details (location), lack of follow-up, and ineffective communication.',
    customerAction:
      '1- Likely negative word-of-mouth.\n2- Possible avoidance of Tata Motors for future purchases or services.',
    customerNpsScore: '-',
    vehicleNumber: 'MH 15 HH 2803',
    vehicleModel: '-',
    breakdownLocation: 'Deshmanega, near Aurangabad Nasik Highway',
    customerName: 'Sagar Ramesh Boradesh',
    agentsInvolved: '1 - Bharati (Support)\n2 - Deepak (Feedback)',
    techniciansInvolved: '1 - Shubham',
    totalCaseDuration: '19 min 7 sec',
    totalHoldTime: '6 min 13 sec',
    emotionalTrend: 'Start - Frustrated\nMid - Dissapointed\nEnd - Neutral',
    totalCalls: '3',
    emotionalAnalysis: 'see: R42, S42',
    direction: 'inbound / outbound',
    transcription: '',
    participantsCount: '',
    callDuration: '',
    callHoldTime: '',
    talkToListenRatio:
      '23: 37 (in a minute, agent is speaking 23 words and listening to 37 words)',
    customerEmotionalTone: '',
    empathyDetection: 'How did the agent empathise',
  },
  'CN-002': {
    caseNumber: 'CN-002',
    caseStatus: 'Open',
    agentPerformance: 'Satisfactory',
    agentPerformanceScore: '3.8/5',
    agentQaRating: 'Good',
    agentQaScore: '40/50 (80%)',
    agentAction:
      "The agent was able to answer most of the customer's questions but failed to provide a follow-up for resolution. The case requires additional attention to meet the customer's expectations.",
    caseType: 'Support',
    severity: 'Medium',
    summary:
      'The customer inquired about the delayed shipment of a vehicle part. The case remains unresolved as the part has not yet been shipped.',
    issueBucket: 'Delayed Shipment',
    issueCause: 'Unavailability of stock',
    brandPerception: 'Neutral',
    brandLoyalty: 'No noticeable change yet.',
    brandTrust:
      'Customer expressed concern over delayed timelines but hasn’t lost complete trust in the brand.',
    brandMentionsCustomer: 'No',
    brandMentionsAgent: 'No',
    competitorMentions: 'Yes, competitor XYZ has faster delivery times.',
    anticipatedSentiment:
      '1- Mild frustration leading to possible loss of trust.\n2- Continued delays could turn loyalty negative.',
    issuesAffectingSentiment:
      '1- Lack of proactive updates.\n2- Delays without reasonable explanation.',
    customerAction: 'Awaiting resolution, no immediate impact on loyalty.',
    customerNpsScore: '7',
    vehicleNumber: 'MH 12 XY 9876',
    vehicleModel: 'Nexon EV',
    breakdownLocation: 'N/A',
    customerName: 'Rajiv Mehta',
    agentsInvolved: '1 - Karan',
    techniciansInvolved: 'None',
    totalCaseDuration: '3 days',
    totalHoldTime: '2 min',
    emotionalTrend: 'Start - Neutral\nMid - Frustrated\nEnd - Mildly Satisfied',
    totalCalls: '1',
    emotionalAnalysis: 'see: R45, S13',
    direction: 'inbound',
    transcription: '',
    participantsCount: '',
    callDuration: '7 min',
    callHoldTime: '2 min',
    talkToListenRatio:
      '25: 75 (customer talked more due to expressing concerns)',
    customerEmotionalTone: 'Mildly frustrated',
    empathyDetection: 'Agent acknowledged the delays and apologized sincerely.',
  },
  'CN-003': {
    caseNumber: 'CN-003',
    caseStatus: 'Closed',
    agentPerformance: 'Excellent',
    agentPerformanceScore: '4.9/5',
    agentQaRating: 'Outstanding',
    agentQaScore: '49/50 (98%)',
    agentAction:
      'The agent demonstrated empathy, took ownership, and resolved the issue promptly.',
    caseType: 'Repair',
    severity: 'Low',
    summary:
      'The customer reported a minor issue with the infotainment system.',
    issueBucket: 'Software Glitch',
    issueCause: 'Outdated software version.',
    brandPerception: 'Positive',
    brandLoyalty: 'Improved due to excellent service.',
    brandTrust: 'Customer praised the brand for efficient service.',
    brandMentionsCustomer: 'No',
    brandMentionsAgent: 'Yes',
    competitorMentions: 'No',
    anticipatedSentiment: 'Positive word-of-mouth.',
    issuesAffectingSentiment: 'None.',
    customerAction: 'Satisfied.',
    customerNpsScore: '10',
    vehicleNumber: 'MH 43 XX 1234',
    vehicleModel: 'Harrier',
    breakdownLocation: 'N/A',
    customerName: 'Priya Kulkarni',
    agentsInvolved: '1 - Sameer',
    techniciansInvolved: '1 - Ramesh',
    totalCaseDuration: '4 hours',
    totalHoldTime: '1 min',
    emotionalTrend: 'Start - Concerned\nMid - Neutral\nEnd - Happy',
    totalCalls: '2',
    emotionalAnalysis: 'see: R48, S16',
    direction: 'inbound',
    transcription: '',
    participantsCount: '',
    callDuration: '5 min',
    callHoldTime: '1 min',
    talkToListenRatio: '45: 55',
    customerEmotionalTone: 'Grateful',
    empathyDetection: 'Agent listened and responded warmly.',
  },
  'CN-004': {
    caseNumber: 'CN-004',
    caseStatus: 'Resolved',
    agentPerformance: 'Good',
    agentPerformanceScore: '4.2/5',
    agentQaRating: 'Satisfactory',
    agentQaScore: '38/50 (76%)',
    agentAction:
      'The agent handled the case promptly and resolved the issue, although follow-up was delayed.',
    caseType: 'Support',
    severity: 'Medium',
    summary:
      'The customer reported a malfunction with the car’s air conditioning system. The issue was identified and resolved, but the customer’s follow-up experience was delayed.',
    issueBucket: 'Air Conditioning',
    issueCause: 'Faulty compressor',
    brandPerception: 'Neutral',
    brandLoyalty: 'No immediate impact.',
    brandTrust:
      'Customer showed trust in the brand but expressed disappointment with the delayed follow-up.',
    brandMentionsCustomer: 'No',
    brandMentionsAgent: 'No',
    competitorMentions: 'No',
    anticipatedSentiment:
      'Neutral with a slight possibility of mild dissatisfaction.',
    issuesAffectingSentiment: 'Delayed follow-up and repair time.',
    customerAction:
      'Likely to continue using the brand with some reservations.',
    customerNpsScore: '6',
    vehicleNumber: 'MH 09 AD 4567',
    vehicleModel: 'Tiago',
    breakdownLocation: 'N/A',
    customerName: 'Ravi Kumar',
    agentsInvolved: '1 - Vikram',
    techniciansInvolved: '1 - Rakesh',
    totalCaseDuration: '5 hours',
    totalHoldTime: '3 min',
    emotionalTrend: 'Start - Annoyed\nMid - Neutral\nEnd - Satisfied',
    totalCalls: '2',
    emotionalAnalysis: 'see: R32, S27',
    direction: 'inbound',
    transcription: '',
    participantsCount: '',
    callDuration: '4 min',
    callHoldTime: '3 min',
    talkToListenRatio:
      '50: 50 (Customer expressed some frustration, but agent remained calm and effective)',
    customerEmotionalTone: 'Frustrated but calm',
    empathyDetection:
      'Agent acknowledged frustration and expressed understanding.',
  },
  'CN-005': {
    caseNumber: 'CN-005',
    caseStatus: 'Pending',
    agentPerformance: 'Average',
    agentPerformanceScore: '3.0/5',
    agentQaRating: 'Needs Improvement',
    agentQaScore: '30/50 (60%)',
    agentAction:
      'The agent was slow to respond and missed some key details during the case resolution process.',
    caseType: 'Complaint',
    severity: 'High',
    summary:
      'The customer had a dispute about the service charges for a recent repair.',
    issueBucket: 'Service Charge Discrepancy',
    issueCause: 'Confusion about pricing policy',
    brandPerception: 'Negative',
    brandLoyalty: 'No',
    brandTrust:
      'Customer is frustrated and feels that the service was overpriced.',
    brandMentionsCustomer: 'No',
    brandMentionsAgent: 'No',
    competitorMentions:
      'Yes, customer considering switching to XYZ competitor.',
    anticipatedSentiment:
      '1- Anger leading to negative sentiment and brand disengagement.\n2- Likely to choose a competitor based on pricing.',
    issuesAffectingSentiment:
      '1- Miscommunication on pricing\n2- No follow-up on the issue.',
    customerAction: 'May look for alternative service providers.',
    customerNpsScore: '-2',
    vehicleNumber: 'MH 04 CR 2345',
    vehicleModel: 'Tata Safari',
    breakdownLocation: 'N/A',
    customerName: 'Anil Patil',
    agentsInvolved: '1 - Neha',
    techniciansInvolved: '1 - Sameer',
    totalCaseDuration: '3 hours',
    totalHoldTime: '5 min',
    emotionalTrend: 'Start - Frustrated\nMid - Angry\nEnd - Disappointed',
    totalCalls: '2',
    emotionalAnalysis: 'see: R23, S38',
    direction: 'inbound',
    transcription: '',
    participantsCount: '',
    callDuration: '7 min',
    callHoldTime: '2 min',
    talkToListenRatio: '30: 70 (Agent struggled to respond quickly)',
    customerEmotionalTone: 'Angry',
    empathyDetection:
      'The agent made several attempts to apologize, but the customer remained upset.',
  },
  'CN-006': {
    caseNumber: 'CN-006',
    caseStatus: 'Resolved',
    agentPerformance: 'Excellent',
    agentPerformanceScore: '5/5',
    agentQaRating: 'Outstanding',
    agentQaScore: '50/50 (100%)',
    agentAction:
      'The agent was prompt, empathetic, and resolved the issue efficiently.',
    caseType: 'Repair',
    severity: 'Medium',
    summary: 'Customer had a malfunctioning brake system.',
    issueBucket: 'Brake System Failure',
    issueCause: 'Worn brake pads',
    brandPerception: 'Positive',
    brandLoyalty: 'Improved',
    brandTrust:
      'The customer expressed appreciation for the prompt and effective resolution.',
    brandMentionsCustomer: 'No',
    brandMentionsAgent: 'Yes',
    competitorMentions: 'No',
    anticipatedSentiment: 'Positive, likely to recommend.',
    issuesAffectingSentiment: 'None.',
    customerAction: 'Likely to remain loyal and continue using Tata services.',
    customerNpsScore: '9',
    vehicleNumber: 'MH 12 AB 5678',
    vehicleModel: 'Altroz',
    breakdownLocation: 'N/A',
    customerName: 'Snehal Joshi',
    agentsInvolved: '1 - Rani',
    techniciansInvolved: '1 - Sandeep',
    totalCaseDuration: '2 hours',
    totalHoldTime: '1 min',
    emotionalTrend: 'Start - Concerned\nMid - Neutral\nEnd - Happy',
    totalCalls: '1',
    emotionalAnalysis: 'see: R12, S18',
    direction: 'inbound',
    transcription: '',
    participantsCount: '',
    callDuration: '5 min',
    callHoldTime: '1 min',
    talkToListenRatio:
      '40: 60 (Customer expressed concerns more than the agent)',
    customerEmotionalTone: 'Relieved',
    empathyDetection:
      'The agent demonstrated a thorough understanding and resolved the issue quickly.',
  },
  'CN-007': {
    caseNumber: 'CN-007',
    caseStatus: 'Pending',
    agentPerformance: 'Average',
    agentPerformanceScore: '3.2/5',
    agentQaRating: 'Needs Improvement',
    agentQaScore: '35/50 (70%)',
    agentAction:
      'The agent was polite but delayed in providing a resolution and unclear in the explanation.',
    caseType: 'Support',
    severity: 'High',
    summary:
      'The customer is reporting an engine warning light issue and a loss of power.',
    issueBucket: 'Engine Warning Light',
    issueCause: 'Sensor malfunction',
    brandPerception: 'Neutral',
    brandLoyalty: 'Low',
    brandTrust:
      'Customer is concerned and frustrated with the delay in resolution.',
    brandMentionsCustomer: 'No',
    brandMentionsAgent: 'No',
    competitorMentions: 'Yes, customer looking into alternatives.',
    anticipatedSentiment:
      '1- Frustration could lead to brand disengagement.\n2- Customer may switch brands if unresolved.',
    issuesAffectingSentiment:
      '1- Delay in troubleshooting.\n2- Lack of clear answers during initial call.',
    customerAction: 'Customer may look into competitor brands.',
    customerNpsScore: '3',
    vehicleNumber: 'MH 06 DG 9876',
    vehicleModel: 'Tata Harrier',
    breakdownLocation: 'N/A',
    customerName: 'Vikrant Patel',
    agentsInvolved: '1 - Kiran',
    techniciansInvolved: 'None',
    totalCaseDuration: '2 days',
    totalHoldTime: '6 min',
    emotionalTrend: 'Start - Concerned\nMid - Frustrated\nEnd - Unsatisfied',
    totalCalls: '3',
    emotionalAnalysis: 'see: R20, S25',
    direction: 'inbound',
    transcription: '',
    participantsCount: '',
    callDuration: '9 min',
    callHoldTime: '3 min',
    talkToListenRatio: '50: 50',
    customerEmotionalTone: 'Frustrated',
    empathyDetection:
      'The agent acknowledged the issue but did not take immediate action to resolve it.',
  },
};
